In [6]:
import pandas as pd
import glob
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [7]:
# Get a list of all CSV files in the directory
csv_files = glob.glob('C:\\Users\\PC\\Products\\Myproducts\\*.csv')

In [8]:
# Check if there are any CSV files in the directory
if len(csv_files) == 0:
    print("No CSV files found in the directory")
else:
    # Initialize an empty list to store the DataFrames
    data = []

    # Loop through the CSV files and read each one into a DataFrame
    for csv_file in csv_files:
        try:
            df = pd.read_csv(csv_file)
            data.append(df)
        except Exception as e:
            print(f"Error reading {csv_file}: {e}")

    # Concatenate the DataFrames into a single DataFrame
    df = pd.concat(data)

C:\Users\PC\AppData\Local\Temp\ipykernel_4416\2301213906.py:11: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

In [9]:
df.head()

,_id,product_title,product_id,product_category,product_url,product_images,price_currency,original_price,selling_price,discount_percentage,parent_url,product_rating,meta_data_1,meta_data_2,review_count,spider_name,created_at,updated_at,validated,meta_data_3
0,65b8b7bc1c72de654d3f7109,Germany DNA Graphic T-Shirt,IU2095,"['Home', 'Men', 'Clothing']",https://www.adidas.co.uk/germany-dna-graphic-t...,"['https://assets.adidas.com/images/w_1080,f_au...",£,28.0,28.0,0.0,NaN,0.0,<h5>Product Description</h5><h5>A GERMANY TEE ...,Color : Black,0.0,adidas,1706604476,NaN,NaN,NaN
1,65b8b7bd1c72de654d3f710a,Colorblock 3-Stripes Swim Boxers,IU1874,"['Home', 'Men', 'Clothing']",https://www.adidas.co.uk/colorblock-3-stripes-...,"['https://assets.adidas.com/images/w_1080,f_au...",£,30.0,30.0,0.0,NaN,4.6,<h5>Product Description</h5><h5>SPORTY SWIM BO...,Color : Blue,7.0,adidas,1706604477,NaN,NaN,NaN
2,65b8b7c71c72de654d3f710b,Germany Beckenbauer Track Top,IU2100,"['Home', 'Football', 'Clothing']",https://www.adidas.co.uk/germany-beckenbauer-t...,"['https://assets.adidas.com/images/w_1080,f_au...",£,85.0,85.0,0.0,NaN,5.0,<h5>Product Description</h5><h5>VINTAGE-INSPIR...,Color : White,7.0,adidas,1706604487,NaN,NaN,NaN
3,65b8b7c91c72de654d3f710c,Germany Pants Kids,IU2091,"['Home', 'Kids', 'Clothing']",https://www.adidas.co.uk/germany-pants-kids/IU...,"['https://assets.adidas.com/images/w_1080,f_au...",£,33.0,33.0,0.0,NaN,0.0,<h5>Product Description</h5><h5>SOFT GERMANY P...,Color : Black,0.0,adidas,1706604489,NaN,NaN,NaN
4,65b8b7ca1c72de654d3f710d,Germany Adicolor Classics 3-Stripes T-Shirt,IU2102,"['Home', 'Football', 'Clothing']",https://www.adidas.co.uk/germany-adicolor-clas...,"['https://assets.adidas.com/images/w_1080,f_au...",£,45.0,45.0,0.0,NaN,4.8,<h5>Product Description</h5><h5>VINTAGE-INSPIR...,Color : White,20.0,adidas,1706604490,NaN,NaN,NaN

In [10]:
# Filter data by spider_name
spider_names = [
    'asos', 'adidas', 'nike', 'sportsdirect', 'argos',
    'decathlon', 'ao', 'currys', 'sephora', 'next', 'amazon'
]
df = df[df['spider_name'].isin(spider_names)]

In [11]:
# Extract relevant columns
df = df[['product_title', 'product_category']]

In [12]:
df

,product_title,product_category
0,Germany DNA Graphic T-Shirt,"['Home', 'Men', 'Clothing']"
1,Colorblock 3-Stripes Swim Boxers,"['Home', 'Men', 'Clothing']"
2,Germany Beckenbauer Track Top,"['Home', 'Football', 'Clothing']"
3,Germany Pants Kids,"['Home', 'Kids', 'Clothing']"
4,Germany Adicolor Classics 3-Stripes T-Shirt,"['Home', 'Football', 'Clothing']"
...,...,...
58,Samsung Galaxy Z Flip3 5G 128GB Smartphone,"['Home', 'Game', 'Technology', 'Audio and Devi..."
59,Ski Goggles SP0053,"['Home', 'Skiing', 'Ski Equipment', 'Ski Goggl..."
60,Lacoste Netflix Shrt Sn32,"['Home', 'Frasers Plus Exclusive Prices', 'USC']"
61,MProtect NP Sn99,"['Home', 'Mens', 'Footwear', 'Trainers']"
62,The Sugar-nator Pointer,"['Home', 'Game', 'Gaming', 'Merchandise', 'Col..."

In [13]:
# Remove duplicates and missing values
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [14]:
df.head()

,product_title,product_category
0,Germany DNA Graphic T-Shirt,"['Home', 'Men', 'Clothing']"
1,Colorblock 3-Stripes Swim Boxers,"['Home', 'Men', 'Clothing']"
2,Germany Beckenbauer Track Top,"['Home', 'Football', 'Clothing']"
3,Germany Pants Kids,"['Home', 'Kids', 'Clothing']"
4,Germany Adicolor Classics 3-Stripes T-Shirt,"['Home', 'Football', 'Clothing']"

In [15]:
# Apply stemming and stopword removal
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

df['product_title'] = df['product_title'].fillna('')
df['product_title'] = df['product_title'].apply(
    lambda x: ' '.join([ps.stem(word) for word in x.lower().split() if word.lower() not in stop_words])
)
df['gender_category'] = df['product_category'].apply(lambda x: 'Mens' if 'mens' in x.lower() else ('Womens' if 'womens' in x.lower() else 'Unisex'))

In [16]:
# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df['product_title'],
    df['gender_category'],
    test_size=0.2,
    random_state=42
)

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer

# Encode categorical variables
label_encoder = LabelEncoder()
df['encoded_product_category'] = label_encoder.fit_transform(df['product_category'])

# Handle text data
tfidf_vectorizer = TfidfVectorizer()
X_product_title_tfidf = tfidf_vectorizer.fit_transform(df['product_title'])

# Split data into features (X) and target variable (y)
X = X_product_title_tfidf
y = df['gender_category']

# Train a RandomForestClassifier model
gender_model = RandomForestClassifier()
gender_model.fit(X, y)

RandomForestClassifier()

In [18]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Evaluate performance on the training data
y_pred = gender_model.predict(X)
accuracy = accuracy_score(y, y_pred)
print("Accuracy:", accuracy)

# Generate a classification report
print("Classification Report:")
print(classification_report(y, y_pred))

# Generate a confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))

# Make predictions on new data (replace X_new with your new data)
# y_new_pred = gender_model.predict(X_new)
# y_new_prob = gender_model.predict_proba(X_new)

Accuracy: 0.9971650138145514
Classification Report:
              precision    recall  f1-score   support

        Mens       0.99      1.00      1.00    120958
      Unisex       1.00      1.00      1.00    253647

    accuracy                           1.00    374605
   macro avg       1.00      1.00      1.00    374605
weighted avg       1.00      1.00      1.00    374605

Confusion Matrix:
[[120547    411]
 [   651 252996]]

In [19]:
df

,product_title,product_category,gender_category,encoded_product_category
0,germani dna graphic t-shirt,"['Home', 'Men', 'Clothing']",Unisex,3048
1,colorblock 3-stripe swim boxer,"['Home', 'Men', 'Clothing']",Unisex,3048
2,germani beckenbau track top,"['Home', 'Football', 'Clothing']",Unisex,2768
3,germani pant kid,"['Home', 'Kids', 'Clothing']",Unisex,2943
4,germani adicolor classic 3-stripe t-shirt,"['Home', 'Football', 'Clothing']",Unisex,2768
...,...,...,...,...
58,samsung galaxi z flip3 5g 128gb smartphon,"['Home', 'Game', 'Technology', 'Audio and Devi...",Unisex,2808
59,ski goggl sp0053,"['Home', 'Skiing', 'Ski Equipment', 'Ski Goggl...",Unisex,3173
60,lacost netflix shrt sn32,"['Home', 'Frasers Plus Exclusive Prices', 'USC']",Unisex,2787
61,mprotect np sn99,"['Home', 'Mens', 'Footwear', 'Trainers']",Mens,3080
62,sugar-n pointer,"['Home', 'Game', 'Gaming', 'Merchandise', 'Col...",Unisex,2797

In [20]:
# Specify the file path where you want to save the CSV file
csv_file_path = 'C:\\Users\\PC\\Products\\Myproducts\\Unzipped\\Test1\\Final_report.csv'

# Save the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)  # Set index=False to avoid writing row indices to the CSV file

# final report
The final report generated from the provided code can be explained step by step as follows:

1. Data Loading and Preprocessing:
   - Multiple CSV files are imported and concatenated into a single DataFrame.
   - The DataFrame is cleaned by removing duplicates and missing values.

2. Text Data Processing:
   - The 'product_title' column is preprocessed by applying stemming and stopword removal using the PorterStemmer and NLTK's stopwords.
   - Categorical variables are encoded using LabelEncoder for the 'product_category' column.

3. Feature Engineering:
   - TF-IDF vectorization is applied to the 'product_title' column to convert text data into numerical features.

4. Target Variable Definition:
   - The 'gender_category' column is derived from the 'product_category' column, categorizing products as 'Mens', 'Womens', or 'Unisex' based on the category information.

5. Model Training and Evaluation:
   - The data is split into training and testing sets using train_test_split.
   - A RandomForestClassifier model is trained on the TF-IDF transformed 'product_title' data to predict the 'gender_category'.
   - The model is evaluated based on its ability to classify products into gender categories.

6. Model Interpretation:
   - The trained RandomForestClassifier model is stored for future predictions and analysis.

7. Additional Steps:
   - The final report includes the encoded product categories, TF-IDF transformed 'product_title' data, and the trained RandomForestClassifier model.
   - The report provides insights into the methodology used for text data processing, feature encoding, and model training.

By following these steps, the final report presents a detailed overview of the data preprocessing, feature engineering, model training, and evaluation process. It showcases the transformation of text data into numerical features, the creation of a predictive model, and the evaluation of the model's performance in classifying products into gender categories based on the provided information.

If you have any specific questions or need further clarification on any step, feel free to ask!